
export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const UPDATE_TEAM = "UPDATE_TEAM";
export const UPDATE_MEMBERS = "UPDATE_MEMBERS";

export const UPDATE_TASKS = "UPDATE_TASKS"; 
export const UPDATE_TASKS = "UPDATE_TASKS"; 
export const ADD_TASK = "ADD_TASK"; 
export const REMOVE_TASK = "REMOVE_TASK"; 

export const UPDATE_ATTEMPTS = "UPDATE_ATTEMPTS";
export const COMPLETE_ATTEMPT = "COMPLETE_ATTEMPT"; 
export const UNDO_ATTEMPT = "UNDO_ATTEMPT"; 